from agent.td3.base_td3_agent import Td3MlpAgent
from agent.td3.ewc_td3_agent import EwcTd3MlpAgent
from agent.td3.si_td3_agent import SiTd3MlpAgent
from agent.td3.agem_td3_agent import AgemTd3MlpAgent
from agent.td3.mh_td3_agent import MultiHeadTd3MlpAgent
from agent.td3.mi_td3_agent import MultiInputTd3MlpAgent
from agent.td3.ewc_mh_td3_agent import EwcMultiHeadTd3MlpAgent
from agent.td3.si_mh_td3_agent import SiMultiHeadTd3MlpAgent
from agent.td3.agem_mh_td3_agent import AgemMultiHeadTd3MlpAgent
from agent.td3.agem_mi_td3_agent import AgemMultiInputTd3MlpAgent
