from base_ppo_agent import PpoMlpAgent
from ewc_ppo_agent import EwcPpoMlpAgent
from si_ppo_agent import SiPpoMlpAgent
from agem_ppo_agent import AgemPpoMlpAgent
from mh_ppo_agent import MultiHeadPpoMlpAgent
from ewc_mh_ppo_agent import EwcMultiHeadPpoMlpAgent
from si_mh_ppo_agent import SiMultiHeadPpoMlpAgent
from agem_mh_ppo_agent import AgemMultiHeadPpoMlpAgent
