from agent.ppo.base_ppo_agent import PpoMlpAgent
from agent.ppo.ewc_ppo_agent import EwcPpoMlpAgent
from agent.ppo.ewc_ppo_agent_v2 import EwcPpoMlpAgentV2
from agent.ppo.si_ppo_agent import SiPpoMlpAgent
from agent.ppo.si_ppo_agent_v2 import SiPpoMlpAgentV2
from agent.ppo.agem_ppo_agent import AgemPpoMlpAgent
from agent.ppo.agem_ppo_agent_v2 import AgemPpoMlpAgentV2
from agent.ppo.mh_ppo_agent import MultiHeadPpoMlpAgent
from agent.ppo.mh_ppo_agent_v2 import MultiHeadPpoMlpAgentV2
from agent.ppo.ewc_mh_ppo_agent import EwcMultiHeadPpoMlpAgent
from agent.ppo.ewc_mh_ppo_agent_v2 import EwcMultiHeadPpoMlpAgentV2
from agent.ppo.si_mh_ppo_agent import SiMultiHeadPpoMlpAgent
from agent.ppo.si_mh_ppo_agent_v2 import SiMultiHeadPpoMlpAgentV2
from agent.ppo.agem_mh_ppo_agent import AgemMultiHeadPpoMlpAgent
from agent.ppo.agem_mh_ppo_agent_v2 import AgemMultiHeadPpoMlpAgentV2
